# -*- coding: utf-8 -*-
"""Comercial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hn7118yF_6IFFrSutewjws-Qay2hiRRv
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

consultores = pd.read_excel('Consultores.xlsx')

lojas = pd.read_excel('Lojas.xlsx')

metas = pd.read_excel('Metas.xlsx')

vendas1T= pd.read_excel('Vendas.xlsx')
vendas2T= pd.read_excel('Vendas_2T.xlsx')

lojas.head()

print(lojas.isnull())

lojas["IdStore"].duplicated().sum()

lojas['Size'].value_counts()

lojas["Size"] = lojas["Size"].replace({
    "SMAL" : "SMALL",
    "MEDIUN" : "MEDIUM",
    "MID" : "MEDIUM",
    "LRGE" : "LARGE"
})

lojas['Size'].value_counts()

"""Em lojas, não foi necessário checar por duplicidade de lojas, pois o IdStore não são duplicados. Houve o ajuste da escrita dos objeto Size, checagem de valores nulos e contagem

**Tratamento Consultores**
"""

consultores.head()

consultores.info()

print(consultores.isnull())

consultores['Role'].value_counts()

consultores["IdSeller"].duplicated().sum()

duplicados_id = consultores[consultores.duplicated(subset=["IdSeller"], keep=False)]
display(duplicados_id)

"""Tudo certo com os valores de Role, Wage, Seller, IdSeller e o tipo de dado também foi validado, apesar de preferir os salários como float, manterei Int pois não há casas decimais. Mas há 3 linhas duplicadas com o mesmo IDSeller. Como o natural é a pessoa ser promovida e não o contrário, vou manter apenas as linhas de Manager para esses IDSeller."""

consultores = consultores[
    (consultores["Role"] == "Sales Manager") |
    (~consultores["IdSeller"].duplicated(keep=False))
]

consultores["IdSeller"].duplicated().sum()
consultores['Role'].value_counts()

"""**Tratamento Metas**"""

metas.head()

metas.info()

metas.isnull().sum()

metas.duplicated(subset=["IdStore", "Date"], keep=False)

"""Metas organizadas por semana, chequei apenas se haviam datas duplicadas de acordo com o ID da loja, para somar a Meta, mas não há. Então consider os dados tratados.

**Tratamento de vendas**
"""

vendas1T.head()

vendas2T.head()

vendas1T.info()

vendas1T["Date"] = pd.to_datetime(vendas1T["Date"], errors="coerce")
vendas2T["Date"] = pd.to_datetime(vendas2T["Date"], errors="coerce")

vendas_total = pd.concat([vendas1T, vendas2T], ignore_index=True)

vendas_total.head()

vendas_total.isnull().sum()

vendas_total.info()

vendas_total.info()

vendas_total["IdPurchase"].duplicated().sum()

"""Levo em conta que o IdPurchase é o indice de uma compra inteira, cada compra tem um ID, uma quantidade de itens e valores diferentes, então não faz sentido apagar as duplicadas nesse caso.

**Tratando as datas**

Para análise temporal, separo as datas em colunas.
"""

vendas_total["Date"] = pd.to_datetime(vendas_total["Date"])
vendas_total["Year"] = vendas_total["Date"].dt.year
vendas_total["Month"] = vendas_total["Date"].dt.month
vendas_total["Quarter"] = "T" + vendas_total["Date"].dt.quarter.astype(str)
vendas_total["Week"] = vendas_total["Date"].dt.isocalendar().week.astype(int)

"""Criei a coluna de quarter, porque eu já fiz essa tratativa de dados de data algumas vezes e quando eu montei o dash, pensei em olhar por trimestre no filtro, em vez de semana, mas acabei olhando o mês, deixei ela na planilha porque pooderia ser útil."""

metas["Date"] = pd.to_datetime(metas["Date"])
metas["Year"] = metas["Date"].dt.year
metas["Month"] = metas["Date"].dt.month
metas["Quarter"] = "T" + metas["Date"].dt.quarter.astype(str)
metas["Week"] = metas["Date"].dt.isocalendar().week.astype(int)

"""Separei as datas no python, mas também seria possível fazer lá dentro. Isso permite trabalhar os gráficos por tempo.

"""

vendas_total.head()

metas.head()

vendas_total.info()

vendas_total["Price"] = vendas_total["Price"].astype(float)
vendas_total.head()

print(vendas1T.columns)
print(vendas2T.columns)

vendas_total.to_excel("vendas_total.xlsx", index=False)
consultores.to_excel("consultores_ok.xlsx", index=False)
lojas.to_excel("lojas_ok.xlsx", index=False)
metas.to_excel("metas_ok.xlsx", index=False)

from google.colab import files

files.download("vendas_total.xlsx")
files.download("consultores_ok.xlsx")
files.download("lojas_ok.xlsx")
files.download("metas_ok.xlsx")

